### ISSUE TITLE
Consider removing datepicker?

### ISSUE THREAD

**Issue by asottile** [Yelp/git-code-debt#52]
I know I never use it after we added click + drag on the graphs.  Should we keep them around?

**Comment by asottile** [comment]
@struys @campaul what are your thoughts?

**Comment by campaul** [comment]
I say kill it, it's basically pointless.

**Comment by campaul** [comment]
I went ahead and made https://github.com/Yelp/git-code-debt/pull/53 since I expect we'll all be in agreement here. This has the nice effect of removing jquery-ui as well.

**Comment by asottile** [comment]
Closed via #53
