### ISSUE TITLE
Use existing repo instead of cloning to temp directory

### ISSUE THREAD

**Issue by johnscancella** [Yelp/git-code-debt#66]
It would be really nice if it could use an existing git repo instead of having to clone it to a temp directory since a really big git repo takes a long time and uses space when I already have it locally.

**Comment by asottile** [comment]
You can! Instead of using a remote repository simply use a path on your filesystem.  The clone it does will not actually check out any files or history for local filesystem repositories (a `--shared` clone).

Is this not what you're observing?

**Comment by johnscancella** [comment]
Ahh I did not realize that it didn't actually do anything since it still said it was cloning to a temp directory

**Comment by asottile** [comment]
cheers!  Thanks for the issue :)

**Comment by Pawamoy** [comment]
Maybe you could add a note / example about that in the README :)

**Comment by asottile** [comment]
Added a quick note in 29145d1fd55ed2af06134895c50ddb32137afca1
