### ISSUE TITLE
git diff stat can fail with missing mode

### ISSUE THREAD

**Issue by struys** [Yelp/git-code-debt#70]
Hitting this assertion
  File "/Users/kstruys/Desktop/git-history/venv-git-history/lib/python2.7/site-packages/git_code_debt/file_diff_stat.py", line 108, in _to_file_diff_stat
    assert mode is not None

(venv-git-history)YELP-KSTRUYS:git-history kstruys$ git --version
git version 2.10.1 (Apple Git-78)
(venv-git-history)YELP-KSTRUYS:git-history kstruys$ pip freeze | grep git-code-debt
git-code-debt==0.8.0

the mode appears to be missing when the diff is only file moves

**Comment by asottile** [comment]
Seems related to #62

**Comment by asottile** [comment]
Ah yeah, this is a forked version of the code before #62 was fixed
